echo -e "---------------------------------tf2linux linker log---------------------------------" > link.log
date >> link.log
echo -e "------------------------------------------------------------------------------------\n" >> link.log

cd tf2_src/game/client

/usr/bin/gcc \
\
-Wl,-Map,obj_client_tf_linux32/debug/client.map -shared -m32 -march=pentium4 -mtune=core2 -msse2 -mfpmath=sse -DVPC -DDEBUG -D_DEBUG -DGNUC -DPOSIX \
-DCOMPILER_GCC -D_DLL_EXT=.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=client -DBINK_VIDEO -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL \
-DDEV_BUILD -DFRAME_POINTER_OMISSION_DISABLED -DREPLAY_ENABLED -DNO_STRING_T -DCLIENT_DLL -DVECTOR -DVERSION_SAFE_STEAM_API_INTERFACES -DPROTECTED_THINGS_ENABLE \
-Dstrncpy=use_Q_strncpy_instead -D_snprintf=use_Q_snprintf_instead -DUSE_WEBM_FOR_REPLAY -DUSES_ECON_ITEMS -DTF_CLIENT_DLL -DUSES_ECON_ITEMS -DENABLE_GC_MATCHMAKING \
-DGLOWS_ENABLE -DUSE_DYNAMIC_ASSET_LOADING -DSIXENSE -DVOTING_ENABLED -DNEXT_BOT -D_EXTERNAL_DLL_EXT=.so -DVPCGAMECAPS=VALVE \
-DPROJECTDIR=/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/client -D_DLL_EXT=.so \
-DSOURCE1=1 -DVPCGAME=valve -D_LINUX=1 -D_POSIX=1 -DLINUX=1 -DPOSIX=1  -D_GLIBCXX_USE_CXX11_ABI=0 -DVPROF_LEVEL=1 -DGNUC -DNO_HOOK_MALLOC \
\
-I/usr/local/include/google/protobuf/ \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/client/generated_proto_tf \
\
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/client/hl2 \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/client/hl2/elements \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/client/tf \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/client/tf/vgui \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/statemachine \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/shared/multiplayer \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/shared/tf \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/gcsdk/steamextra \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/client \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/common \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/public \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/public/tier0 \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/public/tier1 \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/thirdparty/SDL2 \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/vgui2/include \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/vgui2/controls \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/shared \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/client/game_controls \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/thirdparty/sixensesdk/include \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/shared/econ \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/gcsdk/steamextra \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/client/econ \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/client/econ \
\
-Wall -Wno-invalid-offsetof -Wno-multichar -Wno-overloaded-virtual -Wno-write-strings \
-Wno-unused-variable -Wno-unused-function -Winvalid-pch -Wswitch -Wno-unknown-pragmas \
-Wno-unused-parameter -Wno-unused-value -Wno-invalid-offsetof -Wno-float-equal \
-Wno-reorder -Werror=return-type -fdiagnostics-show-option -Wformat -Wformat-security \
\
-fvisibility=hidden -gdwarf-4 -g2 -O0 -pipe  -Usprintf -Ustrncpy -UPROTECTED_THINGS_ENABLE \
-fpch-preprocess -fvar-tracking-assignments -m32 -march=pentium4 -mtune=core2 -msse2 -mfpmath=sse \
-DVPC -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -D_DLL_EXT=.so -D_LINUX -DLINUX -DPOSIX -D_POSIX \
-DDLLNAME=client -DBINK_VIDEO -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DDEV_BUILD \
-DFRAME_POINTER_OMISSION_DISABLED -DREPLAY_ENABLED -DNO_STRING_T -DCLIENT_DLL -DVECTOR -DVERSION_SAFE_STEAM_API_INTERFACES \
-DPROTECTED_THINGS_ENABLE -Dstrncpy=use_Q_strncpy_instead -D_snprintf=use_Q_snprintf_instead -DUSE_WEBM_FOR_REPLAY \
-DUSES_ECON_ITEMS -DTF_CLIENT_DLL -DUSES_ECON_ITEMS -DENABLE_GC_MATCHMAKING -DGLOWS_ENABLE -DUSE_DYNAMIC_ASSET_LOADING \
-DSIXENSE -DVOTING_ENABLED -DNEXT_BOT -D_EXTERNAL_DLL_EXT=.so -DVPCGAMECAPS=VALVE \
-DPROJECTDIR=/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/client \
-D_DLL_EXT=.so -DSOURCE1=1 -DVPCGAME=valve -D_LINUX=1 -D_POSIX=1 -DLINUX=1 -DPOSIX=1  -D_GLIBCXX_USE_CXX11_ABI=0 -DVPROF_LEVEL=1 -DGNUC -DNO_HOOK_MALLOC \
\
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/client/generated_proto_tf \
-I/usr/local/include/google/protobuf/ \
\
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/client/hl2 \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/client/hl2/elements \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/client/tf \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/client/tf/vgui \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/statemachine \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/shared/multiplayer \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/shared/tf \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/gcsdk/steamextra \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/client \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/common \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/public \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/public/tier0 \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/public/tier1 \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/thirdparty/SDL2 \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/vgui2/include \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/vgui2/controls \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/shared \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/client/game_controls \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/thirdparty/sixensesdk/include \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/shared/econ \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/gcsdk/steamextra \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/client/econ \
-I/run/media/dt/5126d622-6bab-492e-9d3d-c8f1263ce69c/tf2linux/tf2_src/game/client/econ \
\
-Wall -Wno-invalid-offsetof -Wno-multichar -Wno-overloaded-virtual -Wno-write-strings -Wno-unused-variable -Wno-unused-function \
-Winvalid-pch -Wswitch -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-value -Wno-invalid-offsetof -Wno-float-equal -Wno-reorder -Werror=return-type \
-fdiagnostics-show-option -Wformat -Wformat-security -fvisibility=hidden -gdwarf-4 -g2 -O0 -pipe  -Usprintf -Ustrncpy -UPROTECTED_THINGS_ENABLE \
-fpch-preprocess -fvar-tracking-assignments -m32 -fstack-protector-strong -fstack-protector-strong  -gdwarf-4 -g2 -O0 \
-Wl,--build-id -m32 -Wl,--no-undefined  \
\
-o ./obj_client_tf_linux32/debug/client.so \
-Xlinker --wrap=fopen -Xlinker --wrap=freopen -Xlinker --wrap=open    -Xlinker --wrap=creat    \
-Xlinker --wrap=access  -Xlinker --wrap=__xstat -Xlinker --wrap=stat  -Xlinker --wrap=lstat   \
-Xlinker --wrap=fopen64 -Xlinker --wrap=open64   -Xlinker --wrap=opendir -Xlinker --wrap=__lxstat \
-Xlinker --wrap=chmod -Xlinker --wrap=chown   -Xlinker --wrap=lchown  -Xlinker --wrap=symlink  \
-Xlinker --wrap=link    -Xlinker --wrap=__lxstat64 -Xlinker --wrap=mknod -Xlinker --wrap=utimes  \
-Xlinker --wrap=unlink  -Xlinker --wrap=rename   -Xlinker --wrap=utime   -Xlinker --wrap=__xstat64 \
-Xlinker --wrap=mount -Xlinker --wrap=mkfifo  -Xlinker --wrap=mkdir   -Xlinker --wrap=rmdir    \
-Xlinker --wrap=scandir -Xlinker --wrap=realpath \
\
-static-libgcc -Wl,--start-group \
\
./obj_client_tf_linux32/debug/compiledcaptionswap.o \
./obj_client_tf_linux32/debug/crypto.o \
./obj_client_tf_linux32/debug/cvarslider.o \
./obj_client_tf_linux32/debug/scriptobject.o \
./obj_client_tf_linux32/debug/imageutils.o \
./obj_client_tf_linux32/debug/language.o \
./obj_client_tf_linux32/debug/timeutils.o \
./obj_client_tf_linux32/debug/randoverride.o \
./obj_client_tf_linux32/debug/blacklisted_server_manager.o \
./obj_client_tf_linux32/debug/steamid.o \
./obj_client_tf_linux32/debug/abuse_report.o \
./obj_client_tf_linux32/debug/abuse_report_ui.o \
./obj_client_tf_linux32/debug/bsp_utils.o \
./obj_client_tf_linux32/debug/c_vote_controller.o \
./obj_client_tf_linux32/debug/econ_consumables.o \
./obj_client_tf_linux32/debug/base_gcmessages.pb.o \
./obj_client_tf_linux32/debug/econ_gcmessages.pb.o \
./obj_client_tf_linux32/debug/gcsystemmsgs.pb.o \
./obj_client_tf_linux32/debug/steammessages.pb.o \
./obj_client_tf_linux32/debug/tf_gcmessages.pb.o \
./obj_client_tf_linux32/debug/hud_vote.o \
./obj_client_tf_linux32/debug/publish_file_dialog.o \
./obj_client_tf_linux32/debug/tf_gc_client.o \
./obj_client_tf_linux32/debug/published_files.o \
./obj_client_tf_linux32/debug/youtubeapi.o \
./obj_client_tf_linux32/debug/achievementmgr.o \
./obj_client_tf_linux32/debug/achievements_hlx.o \
./obj_client_tf_linux32/debug/achievement_saverestore.o \
./obj_client_tf_linux32/debug/activitylist.o \
./obj_client_tf_linux32/debug/ammodef.o \
./obj_client_tf_linux32/debug/animation.o \
./obj_client_tf_linux32/debug/baseachievement.o \
./obj_client_tf_linux32/debug/basecombatcharacter_shared.o \
./obj_client_tf_linux32/debug/basecombatweapon_shared.o \
./obj_client_tf_linux32/debug/baseentity_shared.o \
./obj_client_tf_linux32/debug/basegrenade_shared.o \
./obj_client_tf_linux32/debug/baseparticleentity.o \
./obj_client_tf_linux32/debug/baseplayer_shared.o \
./obj_client_tf_linux32/debug/baseprojectile.o \
./obj_client_tf_linux32/debug/baseviewmodel_shared.o \
./obj_client_tf_linux32/debug/base_playeranimstate.o \
./obj_client_tf_linux32/debug/beam_shared.o \
./obj_client_tf_linux32/debug/cam_thirdperson.o \
./obj_client_tf_linux32/debug/collisionproperty.o \
./obj_client_tf_linux32/debug/death_pose.o \
./obj_client_tf_linux32/debug/debugoverlay_shared.o \
./obj_client_tf_linux32/debug/decals.o \
./obj_client_tf_linux32/debug/attribute_manager.o \
./obj_client_tf_linux32/debug/econ_claimcode.o \
./obj_client_tf_linux32/debug/econ_dynamic_recipe.o \
./obj_client_tf_linux32/debug/econ_entity.o \
./obj_client_tf_linux32/debug/econ_entity_creation.o \
./obj_client_tf_linux32/debug/econ_holidays.o \
./obj_client_tf_linux32/debug/econ_item.o \
./obj_client_tf_linux32/debug/econ_item_constants.o \
./obj_client_tf_linux32/debug/econ_item_description.o \
./obj_client_tf_linux32/debug/econ_item_interface.o \
./obj_client_tf_linux32/debug/econ_item_inventory.o \
./obj_client_tf_linux32/debug/econ_item_preset.o \
./obj_client_tf_linux32/debug/econ_item_schema.o \
./obj_client_tf_linux32/debug/econ_item_system.o \
./obj_client_tf_linux32/debug/econ_item_tools.o \
./obj_client_tf_linux32/debug/econ_item_view.o \
./obj_client_tf_linux32/debug/econ_quests.o \
./obj_client_tf_linux32/debug/econ_store.o \
./obj_client_tf_linux32/debug/econ_storecategory.o \
./obj_client_tf_linux32/debug/econ_wearable.o \
./obj_client_tf_linux32/debug/item_selection_criteria.o \
./obj_client_tf_linux32/debug/localization_provider.o \
./obj_client_tf_linux32/debug/effect_dispatch_data.o \
./obj_client_tf_linux32/debug/ehandle.o \
./obj_client_tf_linux32/debug/entitylist_base.o \
./obj_client_tf_linux32/debug/EntityParticleTrail_Shared.o \
./obj_client_tf_linux32/debug/env_detail_controller.o \
./obj_client_tf_linux32/debug/env_wind_shared.o \
./obj_client_tf_linux32/debug/eventlist.o \
./obj_client_tf_linux32/debug/func_ladder.o \
./obj_client_tf_linux32/debug/gamemovement.o \
./obj_client_tf_linux32/debug/gamerules.o \
./obj_client_tf_linux32/debug/gamerules_register.o \
./obj_client_tf_linux32/debug/GameStats.o \
./obj_client_tf_linux32/debug/gamestringpool.o \
./obj_client_tf_linux32/debug/gamevars_shared.o \
./obj_client_tf_linux32/debug/gc_clientsystem.o \
./obj_client_tf_linux32/debug/gc_replicated_convars.o \
./obj_client_tf_linux32/debug/hintmessage.o \
./obj_client_tf_linux32/debug/hintsystem.o \
./obj_client_tf_linux32/debug/igamesystem.o \
./obj_client_tf_linux32/debug/interval.o \
./obj_client_tf_linux32/debug/lobby.o \
./obj_client_tf_linux32/debug/mapentities_shared.o \
./obj_client_tf_linux32/debug/motd.o \
./obj_client_tf_linux32/debug/movevars_shared.o \
./obj_client_tf_linux32/debug/mp_shareddefs.o \
./obj_client_tf_linux32/debug/multiplayer_animstate.o \
./obj_client_tf_linux32/debug/multiplay_gamerules.o \
./obj_client_tf_linux32/debug/obstacle_pushaway.o \
./obj_client_tf_linux32/debug/particlesystemquery.o \
./obj_client_tf_linux32/debug/particle_parse.o \
./obj_client_tf_linux32/debug/particle_property.o \
./obj_client_tf_linux32/debug/party.o \
./obj_client_tf_linux32/debug/physics_main_shared.o \
./obj_client_tf_linux32/debug/physics_saverestore.o \
./obj_client_tf_linux32/debug/physics_shared.o \
./obj_client_tf_linux32/debug/playerclass_info_parse.o \
./obj_client_tf_linux32/debug/playergroup.o \
./obj_client_tf_linux32/debug/point_bonusmaps_accessor.o \
./obj_client_tf_linux32/debug/point_posecontroller.o \
./obj_client_tf_linux32/debug/precache_register.o \
./obj_client_tf_linux32/debug/predictableid.o \
./obj_client_tf_linux32/debug/predictioncopy.o \
./obj_client_tf_linux32/debug/props_shared.o \
./obj_client_tf_linux32/debug/ragdoll_shared.o \
./obj_client_tf_linux32/debug/replay_gamestats_shared.o \
./obj_client_tf_linux32/debug/rope_helpers.o \
./obj_client_tf_linux32/debug/saverestore.o \
./obj_client_tf_linux32/debug/sceneentity_shared.o \
./obj_client_tf_linux32/debug/sequence_Transitioner.o \
./obj_client_tf_linux32/debug/sheetsimulator.o \
./obj_client_tf_linux32/debug/simtimer.o \
./obj_client_tf_linux32/debug/singleplay_gamerules.o \
./obj_client_tf_linux32/debug/sixense_convars.o \
./obj_client_tf_linux32/debug/SoundEmitterSystem.o \
./obj_client_tf_linux32/debug/soundenvelope.o \
./obj_client_tf_linux32/debug/Sprite.o \
./obj_client_tf_linux32/debug/SpriteTrail.o \
./obj_client_tf_linux32/debug/steamworks_gamestats.o \
./obj_client_tf_linux32/debug/studio_shared.o \
./obj_client_tf_linux32/debug/takedamageinfo.o \
./obj_client_tf_linux32/debug/teamplayroundbased_gamerules.o \
./obj_client_tf_linux32/debug/teamplay_gamerules.o \
./obj_client_tf_linux32/debug/teamplay_round_timer.o \
./obj_client_tf_linux32/debug/test_ehandle.o \
./obj_client_tf_linux32/debug/achievements_tf.o \
./obj_client_tf_linux32/debug/achievements_tf_demoman.o \
./obj_client_tf_linux32/debug/achievements_tf_engineer.o \
./obj_client_tf_linux32/debug/achievements_tf_halloween.o \
./obj_client_tf_linux32/debug/achievements_tf_heavy.o \
./obj_client_tf_linux32/debug/achievements_tf_maps.o \
./obj_client_tf_linux32/debug/achievements_tf_medic.o \
./obj_client_tf_linux32/debug/achievements_tf_mvm.o \
./obj_client_tf_linux32/debug/achievements_tf_pyro.o \
./obj_client_tf_linux32/debug/achievements_tf_replay.o \
./obj_client_tf_linux32/debug/achievements_tf_scout.o \
./obj_client_tf_linux32/debug/achievements_tf_sniper.o \
./obj_client_tf_linux32/debug/achievements_tf_soldier.o \
./obj_client_tf_linux32/debug/achievements_tf_spy.o \
./obj_client_tf_linux32/debug/baseobject_shared.o \
./obj_client_tf_linux32/debug/entity_bonuspack.o \
./obj_client_tf_linux32/debug/entity_capture_flag.o \
./obj_client_tf_linux32/debug/entity_halloween_pickup.o \
./obj_client_tf_linux32/debug/teleport_vortex.o \
./obj_client_tf_linux32/debug/tf_weapon_spellbook.o \
./obj_client_tf_linux32/debug/passtime_convars.o \
./obj_client_tf_linux32/debug/passtime_game_events.o \
./obj_client_tf_linux32/debug/quest_objective_manager.o \
./obj_client_tf_linux32/debug/quest_objective_trackers.o \
./obj_client_tf_linux32/debug/shared_object_tracker.o \
./obj_client_tf_linux32/debug/tf_classdata.o \
./obj_client_tf_linux32/debug/tf_condition.o \
./obj_client_tf_linux32/debug/tf_dropped_weapon.o \
./obj_client_tf_linux32/debug/tf_duckleaderboard.o \
./obj_client_tf_linux32/debug/tf_fx_shared.o \
./obj_client_tf_linux32/debug/tf_gamemovement.o \
./obj_client_tf_linux32/debug/tf_gamerules.o \
./obj_client_tf_linux32/debug/tf_gamestats_shared.o \
./obj_client_tf_linux32/debug/tf_gcmessages.o \
./obj_client_tf_linux32/debug/tf_generic_bomb.o \
./obj_client_tf_linux32/debug/tf_halloween_souls_pickup.o \
./obj_client_tf_linux32/debug/tf_item.o \
./obj_client_tf_linux32/debug/tf_item_inventory.o \
./obj_client_tf_linux32/debug/tf_item_powerup_bottle.o \
./obj_client_tf_linux32/debug/tf_item_schema.o \
./obj_client_tf_linux32/debug/tf_item_system.o \
./obj_client_tf_linux32/debug/tf_item_wearable.o \
./obj_client_tf_linux32/debug/tf_ladder_data.o \
./obj_client_tf_linux32/debug/tf_lobby_server.o \
./obj_client_tf_linux32/debug/tf_logic_halloween_2014.o \
./obj_client_tf_linux32/debug/tf_logic_player_destruction.o \
./obj_client_tf_linux32/debug/tf_logic_robot_destruction.o \
./obj_client_tf_linux32/debug/tf_mann_vs_machine_stats.o \
./obj_client_tf_linux32/debug/tf_mapinfo.o \
./obj_client_tf_linux32/debug/tf_matchmaking_shared.o \
./obj_client_tf_linux32/debug/tf_match_description.o \
./obj_client_tf_linux32/debug/tf_notification.o \
./obj_client_tf_linux32/debug/tf_obj_baseupgrade_shared.o \
./obj_client_tf_linux32/debug/tf_party.o \
./obj_client_tf_linux32/debug/tf_playeranimstate.o \
./obj_client_tf_linux32/debug/tf_playerclass_info_parse.o \
./obj_client_tf_linux32/debug/tf_playerclass_shared.o \
./obj_client_tf_linux32/debug/tf_player_shared.o \
./obj_client_tf_linux32/debug/tf_projectile_base.o \
./obj_client_tf_linux32/debug/tf_projectile_energy_ring.o \
./obj_client_tf_linux32/debug/tf_projectile_nail.o \
./obj_client_tf_linux32/debug/tf_pumpkin_bomb.o \
./obj_client_tf_linux32/debug/tf_quest_editor_panel.o \
./obj_client_tf_linux32/debug/tf_quest_restriction.o \
./obj_client_tf_linux32/debug/tf_rating_data.o \
./obj_client_tf_linux32/debug/tf_revive.o \
./obj_client_tf_linux32/debug/tf_robot_destruction_robot.o \
./obj_client_tf_linux32/debug/tf_shareddefs.o \
./obj_client_tf_linux32/debug/tf_survey_questions.o \
./obj_client_tf_linux32/debug/tf_upgrades_shared.o \
./obj_client_tf_linux32/debug/tf_usermessages.o \
./obj_client_tf_linux32/debug/tf_viewmodel.o \
./obj_client_tf_linux32/debug/tf_wardata.o \
./obj_client_tf_linux32/debug/tf_weaponbase.o \
./obj_client_tf_linux32/debug/tf_weaponbase_grenadeproj.o \
./obj_client_tf_linux32/debug/tf_weaponbase_gun.o \
./obj_client_tf_linux32/debug/tf_weaponbase_melee.o \
./obj_client_tf_linux32/debug/tf_weaponbase_merasmus_grenade.o \
./obj_client_tf_linux32/debug/tf_weaponbase_rocket.o \
./obj_client_tf_linux32/debug/tf_weapon_bat.o \
./obj_client_tf_linux32/debug/tf_weapon_bonesaw.o \
./obj_client_tf_linux32/debug/tf_weapon_bottle.o \
./obj_client_tf_linux32/debug/tf_weapon_buff_item.o \
./obj_client_tf_linux32/debug/tf_weapon_club.o \
./obj_client_tf_linux32/debug/tf_weapon_compound_bow.o \
./obj_client_tf_linux32/debug/tf_weapon_fireaxe.o \
./obj_client_tf_linux32/debug/tf_weapon_fists.o \
./obj_client_tf_linux32/debug/tf_weapon_flamethrower.o \
./obj_client_tf_linux32/debug/tf_weapon_flaregun.o \
./obj_client_tf_linux32/debug/tf_weapon_grapplinghook.o \
./obj_client_tf_linux32/debug/tf_weapon_grenadelauncher.o \
./obj_client_tf_linux32/debug/tf_weapon_grenade_pipebomb.o \
./obj_client_tf_linux32/debug/tf_weapon_invis.o \
./obj_client_tf_linux32/debug/tf_weapon_jar.o \
./obj_client_tf_linux32/debug/tf_weapon_knife.o \
./obj_client_tf_linux32/debug/tf_weapon_laser_pointer.o \
./obj_client_tf_linux32/debug/tf_weapon_lunchbox.o \
./obj_client_tf_linux32/debug/tf_weapon_mechanical_arm.o \
./obj_client_tf_linux32/debug/tf_weapon_medigun.o \
./obj_client_tf_linux32/debug/tf_weapon_minigun.o \
./obj_client_tf_linux32/debug/tf_weapon_parachute.o \
./obj_client_tf_linux32/debug/tf_weapon_parse.o \
./obj_client_tf_linux32/debug/tf_weapon_particle_cannon.o \
./obj_client_tf_linux32/debug/tf_weapon_passtime_gun.o \
./obj_client_tf_linux32/debug/tf_weapon_pda.o \
./obj_client_tf_linux32/debug/tf_weapon_pipebomblauncher.o \
./obj_client_tf_linux32/debug/tf_weapon_pistol.o \
./obj_client_tf_linux32/debug/tf_weapon_raygun.o \
./obj_client_tf_linux32/debug/tf_weapon_revolver.o \
./obj_client_tf_linux32/debug/tf_weapon_rocketlauncher.o \
./obj_client_tf_linux32/debug/tf_weapon_shotgun.o \
./obj_client_tf_linux32/debug/tf_weapon_shovel.o \
./obj_client_tf_linux32/debug/tf_weapon_smg.o \
./obj_client_tf_linux32/debug/tf_weapon_sniperrifle.o \
./obj_client_tf_linux32/debug/tf_weapon_sword.o \
./obj_client_tf_linux32/debug/tf_weapon_syringegun.o \
./obj_client_tf_linux32/debug/tf_weapon_throwable.o \
./obj_client_tf_linux32/debug/tf_weapon_wrench.o \
./obj_client_tf_linux32/debug/tf_wearable_item_demoshield.o \
./obj_client_tf_linux32/debug/tf_wearable_levelable_item.o \
./obj_client_tf_linux32/debug/tf_xp_source.o \
./obj_client_tf_linux32/debug/usercmd.o \
./obj_client_tf_linux32/debug/usermessages.o \
./obj_client_tf_linux32/debug/util_shared.o \
./obj_client_tf_linux32/debug/vehicle_viewblend_shared.o \
./obj_client_tf_linux32/debug/voice_banmgr.o \
./obj_client_tf_linux32/debug/voice_status.o \
./obj_client_tf_linux32/debug/weapon_ifmbase.o \
./obj_client_tf_linux32/debug/weapon_ifmbasecamera.o \
./obj_client_tf_linux32/debug/weapon_ifmsteadycam.o \
./obj_client_tf_linux32/debug/weapon_parse.o \
./obj_client_tf_linux32/debug/ugc_utils.o \
./obj_client_tf_linux32/debug/bone_accessor.o \
./obj_client_tf_linux32/debug/bone_setup.o \
./obj_client_tf_linux32/debug/client_class.o \
./obj_client_tf_linux32/debug/collisionutils.o \
./obj_client_tf_linux32/debug/crtmemdebug.o \
./obj_client_tf_linux32/debug/dt_recv.o \
./obj_client_tf_linux32/debug/dt_utlvector_common.o \
./obj_client_tf_linux32/debug/dt_utlvector_recv.o \
./obj_client_tf_linux32/debug/filesystem_helpers.o \
./obj_client_tf_linux32/debug/haptic_msgs.o \
./obj_client_tf_linux32/debug/interpolatortypes.o \
./obj_client_tf_linux32/debug/jigglebones.o \
./obj_client_tf_linux32/debug/networkvar.o \
./obj_client_tf_linux32/debug/posedebugger.o \
./obj_client_tf_linux32/debug/renamed_recvtable_compat.o \
./obj_client_tf_linux32/debug/rope_physics.o \
./obj_client_tf_linux32/debug/scratchpad3d.o \
./obj_client_tf_linux32/debug/ScratchPadUtils.o \
./obj_client_tf_linux32/debug/sentence.o \
./obj_client_tf_linux32/debug/simple_physics.o \
./obj_client_tf_linux32/debug/SoundParametersInternal.o \
./obj_client_tf_linux32/debug/stringregistry.o \
./obj_client_tf_linux32/debug/studio.o \
./obj_client_tf_linux32/debug/memoverride.o \
./obj_client_tf_linux32/debug/bonelist.o \
./obj_client_tf_linux32/debug/vallocator.o \
./obj_client_tf_linux32/debug/vgui_controls.o \
./obj_client_tf_linux32/debug/achievement_notification_panel.o \
./obj_client_tf_linux32/debug/alphamaterialproxy.o \
./obj_client_tf_linux32/debug/animatedentitytextureproxy.o \
./obj_client_tf_linux32/debug/animatedoffsettextureproxy.o \
./obj_client_tf_linux32/debug/animatedtextureproxy.o \
./obj_client_tf_linux32/debug/AnimateSpecificTextureProxy.o \
./obj_client_tf_linux32/debug/baseanimatedtextureproxy.o \
./obj_client_tf_linux32/debug/baseclientrendertargets.o \
./obj_client_tf_linux32/debug/basepresence.o \
./obj_client_tf_linux32/debug/beamdraw.o \
./obj_client_tf_linux32/debug/bone_merge_cache.o \
./obj_client_tf_linux32/debug/camomaterialproxy.o \
./obj_client_tf_linux32/debug/cdll_bounded_cvars.o \
./obj_client_tf_linux32/debug/cdll_client_int.o \
./obj_client_tf_linux32/debug/cdll_util.o \
./obj_client_tf_linux32/debug/classmap.o \
./obj_client_tf_linux32/debug/clienteffectprecachesystem.o \
./obj_client_tf_linux32/debug/cliententitylist.o \
./obj_client_tf_linux32/debug/clientleafsystem.o \
./obj_client_tf_linux32/debug/clientmode_shared.o \
./obj_client_tf_linux32/debug/clientshadowmgr.o \
./obj_client_tf_linux32/debug/clientsideeffects.o \
./obj_client_tf_linux32/debug/clientsideeffects_test.o \
./obj_client_tf_linux32/debug/clientsteamcontext.o \
./obj_client_tf_linux32/debug/client_factorylist.o \
./obj_client_tf_linux32/debug/client_thinklist.o \
./obj_client_tf_linux32/debug/client_virtualreality.o \
./obj_client_tf_linux32/debug/cl_mat_stub.o \
./obj_client_tf_linux32/debug/colorcorrectionmgr.o \
./obj_client_tf_linux32/debug/commentary_modelviewer.o \
./obj_client_tf_linux32/debug/c_ai_basehumanoid.o \
./obj_client_tf_linux32/debug/c_ai_basenpc.o \
./obj_client_tf_linux32/debug/c_baseanimating.o \
./obj_client_tf_linux32/debug/c_baseanimatingoverlay.o \
./obj_client_tf_linux32/debug/c_basecombatcharacter.o \
./obj_client_tf_linux32/debug/c_basecombatweapon.o \
./obj_client_tf_linux32/debug/c_basedoor.o \
./obj_client_tf_linux32/debug/c_baseentity.o \
./obj_client_tf_linux32/debug/c_baseflex.o \
./obj_client_tf_linux32/debug/c_baseplayer.o \
./obj_client_tf_linux32/debug/c_basetempentity.o \
./obj_client_tf_linux32/debug/c_baseviewmodel.o \
./obj_client_tf_linux32/debug/c_breakableprop.o \
./obj_client_tf_linux32/debug/c_colorcorrection.o \
./obj_client_tf_linux32/debug/c_colorcorrectionvolume.o \
./obj_client_tf_linux32/debug/c_dynamiclight.o \
./obj_client_tf_linux32/debug/c_effects.o \
./obj_client_tf_linux32/debug/c_entitydissolve.o \
./obj_client_tf_linux32/debug/c_entityparticletrail.o \
./obj_client_tf_linux32/debug/c_env_fog_controller.o \
./obj_client_tf_linux32/debug/c_env_particlescript.o \
./obj_client_tf_linux32/debug/c_env_projectedtexture.o \
./obj_client_tf_linux32/debug/c_env_screenoverlay.o \
./obj_client_tf_linux32/debug/c_env_tonemap_controller.o \
./obj_client_tf_linux32/debug/c_fire_smoke.o \
./obj_client_tf_linux32/debug/c_fish.o \
./obj_client_tf_linux32/debug/c_func_areaportalwindow.o \
./obj_client_tf_linux32/debug/c_func_breakablesurf.o \
./obj_client_tf_linux32/debug/c_func_conveyor.o \
./obj_client_tf_linux32/debug/c_func_dust.o \
./obj_client_tf_linux32/debug/c_func_lod.o \
./obj_client_tf_linux32/debug/c_func_occluder.o \
./obj_client_tf_linux32/debug/c_func_reflective_glass.o \
./obj_client_tf_linux32/debug/c_func_rotating.o \
./obj_client_tf_linux32/debug/c_func_smokevolume.o \
./obj_client_tf_linux32/debug/c_func_tracktrain.o \
./obj_client_tf_linux32/debug/c_gib.o \
./obj_client_tf_linux32/debug/c_hairball.o \
./obj_client_tf_linux32/debug/c_impact_effects.o \
./obj_client_tf_linux32/debug/c_info_overlay_accessor.o \
./obj_client_tf_linux32/debug/c_lightglow.o \
./obj_client_tf_linux32/debug/C_MaterialModifyControl.o \
./obj_client_tf_linux32/debug/c_movie_explosion.o \
./obj_client_tf_linux32/debug/c_particle_fire.o \
./obj_client_tf_linux32/debug/c_particle_smokegrenade.o \
./obj_client_tf_linux32/debug/c_particle_system.o \
./obj_client_tf_linux32/debug/c_physbox.o \
./obj_client_tf_linux32/debug/c_physicsprop.o \
./obj_client_tf_linux32/debug/c_physmagnet.o \
./obj_client_tf_linux32/debug/c_pixel_visibility.o \
./obj_client_tf_linux32/debug/c_plasma.o \
./obj_client_tf_linux32/debug/c_playerresource.o \
./obj_client_tf_linux32/debug/c_point_camera.o \
./obj_client_tf_linux32/debug/c_point_commentary_node.o \
./obj_client_tf_linux32/debug/c_props.o \
./obj_client_tf_linux32/debug/c_prop_vehicle.o \
./obj_client_tf_linux32/debug/c_ragdoll_manager.o \
./obj_client_tf_linux32/debug/c_recipientfilter.o \
./obj_client_tf_linux32/debug/c_rope.o \
./obj_client_tf_linux32/debug/c_rumble.o \
./obj_client_tf_linux32/debug/c_sceneentity.o \
./obj_client_tf_linux32/debug/c_shadowcontrol.o \
./obj_client_tf_linux32/debug/c_slideshow_display.o \
./obj_client_tf_linux32/debug/c_smokestack.o \
./obj_client_tf_linux32/debug/c_smoke_trail.o \
./obj_client_tf_linux32/debug/c_soundscape.o \
./obj_client_tf_linux32/debug/c_spotlight_end.o \
./obj_client_tf_linux32/debug/c_sprite.o \
./obj_client_tf_linux32/debug/c_sprite_perfmonitor.o \
./obj_client_tf_linux32/debug/c_steamjet.o \
./obj_client_tf_linux32/debug/c_stickybolt.o \
./obj_client_tf_linux32/debug/c_sun.o \
./obj_client_tf_linux32/debug/c_te.o \
./obj_client_tf_linux32/debug/c_team.o \
./obj_client_tf_linux32/debug/c_team_objectiveresource.o \
./obj_client_tf_linux32/debug/c_team_train_watcher.o \
./obj_client_tf_linux32/debug/c_tesla.o \
./obj_client_tf_linux32/debug/c_testtraceline.o \
./obj_client_tf_linux32/debug/c_test_proxytoggle.o \
./obj_client_tf_linux32/debug/c_te_armorricochet.o \
./obj_client_tf_linux32/debug/c_te_basebeam.o \
./obj_client_tf_linux32/debug/c_te_beamentpoint.o \
./obj_client_tf_linux32/debug/c_te_beaments.o \
./obj_client_tf_linux32/debug/c_te_beamfollow.o \
./obj_client_tf_linux32/debug/c_te_beamlaser.o \
./obj_client_tf_linux32/debug/c_te_beampoints.o \
./obj_client_tf_linux32/debug/c_te_beamring.o \
./obj_client_tf_linux32/debug/c_te_beamringpoint.o \
./obj_client_tf_linux32/debug/c_te_beamspline.o \
./obj_client_tf_linux32/debug/c_te_bloodsprite.o \
./obj_client_tf_linux32/debug/c_te_bloodstream.o \
./obj_client_tf_linux32/debug/c_te_breakmodel.o \
./obj_client_tf_linux32/debug/c_te_bspdecal.o \
./obj_client_tf_linux32/debug/c_te_bubbles.o \
./obj_client_tf_linux32/debug/c_te_bubbletrail.o \
./obj_client_tf_linux32/debug/c_te_clientprojectile.o \
./obj_client_tf_linux32/debug/c_te_decal.o \
./obj_client_tf_linux32/debug/c_te_dynamiclight.o \
./obj_client_tf_linux32/debug/c_te_effect_dispatch.o \
./obj_client_tf_linux32/debug/c_te_energysplash.o \
./obj_client_tf_linux32/debug/c_te_explosion.o \
./obj_client_tf_linux32/debug/c_te_fizz.o \
./obj_client_tf_linux32/debug/c_te_footprint.o \
./obj_client_tf_linux32/debug/c_te_glassshatter.o \
./obj_client_tf_linux32/debug/c_te_glowsprite.o \
./obj_client_tf_linux32/debug/c_te_impact.o \
./obj_client_tf_linux32/debug/c_te_killplayerattachments.o \
./obj_client_tf_linux32/debug/c_te_largefunnel.o \
./obj_client_tf_linux32/debug/c_te_legacytempents.o \
./obj_client_tf_linux32/debug/c_te_muzzleflash.o \
./obj_client_tf_linux32/debug/c_te_particlesystem.o \
./obj_client_tf_linux32/debug/c_te_physicsprop.o \
./obj_client_tf_linux32/debug/c_te_playerdecal.o \
./obj_client_tf_linux32/debug/c_te_projecteddecal.o \
./obj_client_tf_linux32/debug/c_te_showline.o \
./obj_client_tf_linux32/debug/c_te_smoke.o \
./obj_client_tf_linux32/debug/c_te_sparks.o \
./obj_client_tf_linux32/debug/c_te_sprite.o \
./obj_client_tf_linux32/debug/c_te_spritespray.o \
./obj_client_tf_linux32/debug/c_te_worlddecal.o \
./obj_client_tf_linux32/debug/c_tracer.o \
./obj_client_tf_linux32/debug/c_user_message_register.o \
./obj_client_tf_linux32/debug/c_vehicle_choreo_generic.o \
./obj_client_tf_linux32/debug/c_vehicle_jeep.o \
./obj_client_tf_linux32/debug/c_vguiscreen.o \
./obj_client_tf_linux32/debug/C_WaterLODControl.o \
./obj_client_tf_linux32/debug/c_world.o \
./obj_client_tf_linux32/debug/detailobjectsystem.o \
./obj_client_tf_linux32/debug/dummyproxy.o \
./obj_client_tf_linux32/debug/backpack_panel.o \
./obj_client_tf_linux32/debug/base_loadout_panel.o \
./obj_client_tf_linux32/debug/client_community_market.o \
./obj_client_tf_linux32/debug/confirm_delete_dialog.o \
./obj_client_tf_linux32/debug/confirm_dialog.o \
./obj_client_tf_linux32/debug/econ_controls.o \
./obj_client_tf_linux32/debug/econ_notifications.o \
./obj_client_tf_linux32/debug/econ_sample_rootui.o \
./obj_client_tf_linux32/debug/econ_trading.o \
./obj_client_tf_linux32/debug/item_confirm_delete_dialog.o \
./obj_client_tf_linux32/debug/item_model_panel.o \
./obj_client_tf_linux32/debug/item_pickup_panel.o \
./obj_client_tf_linux32/debug/item_rental_ui.o \
./obj_client_tf_linux32/debug/item_selection_panel.o \
./obj_client_tf_linux32/debug/item_style_select_dialog.o \
./obj_client_tf_linux32/debug/local_steam_shared_object_listener.o \
./obj_client_tf_linux32/debug/store_page.o \
./obj_client_tf_linux32/debug/store_page_halloween.o \
./obj_client_tf_linux32/debug/store_page_new.o \
./obj_client_tf_linux32/debug/store_panel.o \
./obj_client_tf_linux32/debug/store_preview_item.o \
./obj_client_tf_linux32/debug/store_viewcart.o \
./obj_client_tf_linux32/debug/custom_texture_cache.o \
./obj_client_tf_linux32/debug/custom_texture_tool.o \
./obj_client_tf_linux32/debug/decoder_ring_tool.o \
./obj_client_tf_linux32/debug/gift_wrap_tool.o \
./obj_client_tf_linux32/debug/paint_can_tool.o \
./obj_client_tf_linux32/debug/rename_tool_ui.o \
./obj_client_tf_linux32/debug/tool_items.o \
./obj_client_tf_linux32/debug/trading_start_dialog.o \
./obj_client_tf_linux32/debug/EffectsClient.o \
./obj_client_tf_linux32/debug/entityoriginmaterialproxy.o \
./obj_client_tf_linux32/debug/entity_client_tools.o \
./obj_client_tf_linux32/debug/flashlighteffect.o \
./obj_client_tf_linux32/debug/functionproxy.o \
./obj_client_tf_linux32/debug/fx.o \
./obj_client_tf_linux32/debug/fx_blood.o \
./obj_client_tf_linux32/debug/fx_cube.o \
./obj_client_tf_linux32/debug/fx_discreetline.o \
./obj_client_tf_linux32/debug/fx_envelope.o \
./obj_client_tf_linux32/debug/fx_explosion.o \
./obj_client_tf_linux32/debug/fx_fleck.o \
./obj_client_tf_linux32/debug/fx_impact.o \
./obj_client_tf_linux32/debug/fx_interpvalue.o \
./obj_client_tf_linux32/debug/fx_line.o \
./obj_client_tf_linux32/debug/fx_quad.o \
./obj_client_tf_linux32/debug/fx_shelleject.o \
./obj_client_tf_linux32/debug/fx_sparks.o \
./obj_client_tf_linux32/debug/fx_staticline.o \
./obj_client_tf_linux32/debug/fx_tracer.o \
./obj_client_tf_linux32/debug/fx_trail.o \
./obj_client_tf_linux32/debug/fx_water.o \
./obj_client_tf_linux32/debug/gametrace_client.o \
./obj_client_tf_linux32/debug/basemodelpanel.o \
./obj_client_tf_linux32/debug/basemodel_panel.o \
./obj_client_tf_linux32/debug/baseviewport.o \
./obj_client_tf_linux32/debug/buymenu.o \
./obj_client_tf_linux32/debug/buysubmenu.o \
./obj_client_tf_linux32/debug/classmenu.o \
./obj_client_tf_linux32/debug/ClientScoreBoardDialog.o \
./obj_client_tf_linux32/debug/commandmenu.o \
./obj_client_tf_linux32/debug/IconPanel.o \
./obj_client_tf_linux32/debug/intromenu.o \
./obj_client_tf_linux32/debug/MapOverview.o \
./obj_client_tf_linux32/debug/navigationpanel.o \
./obj_client_tf_linux32/debug/NavProgress.o \
./obj_client_tf_linux32/debug/slideshowpanel.o \
./obj_client_tf_linux32/debug/SpectatorGUI.o \
./obj_client_tf_linux32/debug/teammenu.o \
./obj_client_tf_linux32/debug/vguitextwindow.o \
./obj_client_tf_linux32/debug/geiger.o \
./obj_client_tf_linux32/debug/glow_outline_effect.o \
./obj_client_tf_linux32/debug/glow_overlay.o \
./obj_client_tf_linux32/debug/history_resource.o \
./obj_client_tf_linux32/debug/C_Func_Monitor.o \
./obj_client_tf_linux32/debug/c_waterbullet.o \
./obj_client_tf_linux32/debug/hud_autoaim.o \
./obj_client_tf_linux32/debug/hud_filmdemo.o \
./obj_client_tf_linux32/debug/hud_hdrdemo.o \
./obj_client_tf_linux32/debug/hltvcamera.o \
./obj_client_tf_linux32/debug/hud.o \
./obj_client_tf_linux32/debug/hud_animationinfo.o \
./obj_client_tf_linux32/debug/hud_baseachievement_tracker.o \
./obj_client_tf_linux32/debug/hud_basechat.o \
./obj_client_tf_linux32/debug/hud_basetimer.o \
./obj_client_tf_linux32/debug/hud_base_account.o \
./obj_client_tf_linux32/debug/hud_bitmapnumericdisplay.o \
./obj_client_tf_linux32/debug/hud_closecaption.o \
./obj_client_tf_linux32/debug/hud_controlpointicons.o \
./obj_client_tf_linux32/debug/hud_crosshair.o \
./obj_client_tf_linux32/debug/hud_element_helper.o \
./obj_client_tf_linux32/debug/hud_hintdisplay.o \
./obj_client_tf_linux32/debug/hud_lcd.o \
./obj_client_tf_linux32/debug/hud_msg.o \
./obj_client_tf_linux32/debug/hud_numericdisplay.o \
./obj_client_tf_linux32/debug/hud_pdump.o \
./obj_client_tf_linux32/debug/hud_redraw.o \
./obj_client_tf_linux32/debug/hud_vehicle.o \
./obj_client_tf_linux32/debug/hud_vguiscreencursor.o \
./obj_client_tf_linux32/debug/hud_voicestatus.o \
./obj_client_tf_linux32/debug/hud_weapon.o \
./obj_client_tf_linux32/debug/initializer.o \
./obj_client_tf_linux32/debug/interpolatedvar.o \
./obj_client_tf_linux32/debug/in_camera.o \
./obj_client_tf_linux32/debug/in_joystick.o \
./obj_client_tf_linux32/debug/in_main.o \
./obj_client_tf_linux32/debug/in_mouse.o \
./obj_client_tf_linux32/debug/in_steamcontroller.o \
./obj_client_tf_linux32/debug/IsNPCProxy.o \
./obj_client_tf_linux32/debug/lampbeamproxy.o \
./obj_client_tf_linux32/debug/lamphaloproxy.o \
./obj_client_tf_linux32/debug/mathproxy.o \
./obj_client_tf_linux32/debug/matrixproxy.o \
./obj_client_tf_linux32/debug/menu.o \
./obj_client_tf_linux32/debug/message.o \
./obj_client_tf_linux32/debug/movehelper_client.o \
./obj_client_tf_linux32/debug/mp3player.o \
./obj_client_tf_linux32/debug/mumble.o \
./obj_client_tf_linux32/debug/C_NextBot.o \
./obj_client_tf_linux32/debug/panelmetaclassmgr.o \
./obj_client_tf_linux32/debug/particlemgr.o \
./obj_client_tf_linux32/debug/particlesphererenderer.o \
./obj_client_tf_linux32/debug/particles_attractor.o \
./obj_client_tf_linux32/debug/particles_ez.o \
./obj_client_tf_linux32/debug/particles_localspace.o \
./obj_client_tf_linux32/debug/particles_new.o \
./obj_client_tf_linux32/debug/particles_simple.o \
./obj_client_tf_linux32/debug/particle_collision.o \
./obj_client_tf_linux32/debug/particle_litsmokeemitter.o \
./obj_client_tf_linux32/debug/particle_proxies.o \
./obj_client_tf_linux32/debug/particle_simple3d.o \
./obj_client_tf_linux32/debug/perfvisualbenchmark.o \
./obj_client_tf_linux32/debug/physics.o \
./obj_client_tf_linux32/debug/physics_main_client.o \
./obj_client_tf_linux32/debug/physpropclientside.o \
./obj_client_tf_linux32/debug/playerandobjectenumerator.o \
./obj_client_tf_linux32/debug/playerspawncache.o \
./obj_client_tf_linux32/debug/prediction.o \
./obj_client_tf_linux32/debug/proxyentity.o \
./obj_client_tf_linux32/debug/ProxyHealth.o \
./obj_client_tf_linux32/debug/proxyplayer.o \
./obj_client_tf_linux32/debug/proxypupil.o \
./obj_client_tf_linux32/debug/ragdoll.o \
./obj_client_tf_linux32/debug/recvproxy.o \
./obj_client_tf_linux32/debug/rendertexture.o \
./obj_client_tf_linux32/debug/cdll_replay.o \
./obj_client_tf_linux32/debug/gamedefs.o \
./obj_client_tf_linux32/debug/genericclassbased_replay.o \
./obj_client_tf_linux32/debug/replaycamera.o \
./obj_client_tf_linux32/debug/replayperformanceplaybackhandler.o \
./obj_client_tf_linux32/debug/replayrenderer.o \
./obj_client_tf_linux32/debug/replayvideo.o \
./obj_client_tf_linux32/debug/replayyoutubeapi.o \
./obj_client_tf_linux32/debug/replayyoutubeapi_key.o \
./obj_client_tf_linux32/debug/replay_ragdoll.o \
./obj_client_tf_linux32/debug/replay_screenshot.o \
./obj_client_tf_linux32/debug/replaybrowserbasepage.o \
./obj_client_tf_linux32/debug/replaybrowserbasepanel.o \
./obj_client_tf_linux32/debug/replaybrowserdetailspanel.o \
./obj_client_tf_linux32/debug/replaybrowseritemmanager.o \
./obj_client_tf_linux32/debug/replaybrowserlistitempanel.o \
./obj_client_tf_linux32/debug/replaybrowserlistpanel.o \
./obj_client_tf_linux32/debug/replaybrowsermainpanel.o \
./obj_client_tf_linux32/debug/replaybrowsermovieplayerpanel.o \
./obj_client_tf_linux32/debug/replaybrowserpreviewpanel.o \
./obj_client_tf_linux32/debug/replaybrowserrenderdialog.o \
./obj_client_tf_linux32/debug/replayconfirmquitdlg.o \
./obj_client_tf_linux32/debug/replayinputpanel.o \
./obj_client_tf_linux32/debug/replaymessagepanel.o \
./obj_client_tf_linux32/debug/replayperformanceeditor.o \
./obj_client_tf_linux32/debug/replayperformancesavedlg.o \
./obj_client_tf_linux32/debug/replayreminderpanel.o \
./obj_client_tf_linux32/debug/replayrenderoverlay.o \
./obj_client_tf_linux32/debug/ScreenSpaceEffects.o \
./obj_client_tf_linux32/debug/simple_keys.o \
./obj_client_tf_linux32/debug/smoke_fog_overlay.o \
./obj_client_tf_linux32/debug/splinepatch.o \
./obj_client_tf_linux32/debug/spritemodel.o \
./obj_client_tf_linux32/debug/stdafx.o \
./obj_client_tf_linux32/debug/studio_stats.o \
./obj_client_tf_linux32/debug/TeamBitmapImage.o \
./obj_client_tf_linux32/debug/texturescrollmaterialproxy.o \
./obj_client_tf_linux32/debug/text_message.o \
./obj_client_tf_linux32/debug/c_bot_npc.o \
./obj_client_tf_linux32/debug/c_bot_npc_minion.o \
./obj_client_tf_linux32/debug/c_tf_bot_hint_engineer_nest.o \
./obj_client_tf_linux32/debug/clientmode_tf.o \
./obj_client_tf_linux32/debug/c_baseobject.o \
./obj_client_tf_linux32/debug/c_entity_bird.o \
./obj_client_tf_linux32/debug/c_entity_currencypack.o \
./obj_client_tf_linux32/debug/c_func_capture_zone.o \
./obj_client_tf_linux32/debug/c_func_forcefield.o \
./obj_client_tf_linux32/debug/c_func_passtime_goal.o \
./obj_client_tf_linux32/debug/c_func_respawnroom.o \
./obj_client_tf_linux32/debug/c_monster_resource.o \
./obj_client_tf_linux32/debug/c_obj_dispenser.o \
./obj_client_tf_linux32/debug/c_obj_sapper.o \
./obj_client_tf_linux32/debug/c_obj_sentrygun.o \
./obj_client_tf_linux32/debug/c_obj_teleporter.o \
./obj_client_tf_linux32/debug/c_playerattachedmodel.o \
./obj_client_tf_linux32/debug/c_playerrelativemodel.o \
./obj_client_tf_linux32/debug/c_tf_ammo_pack.o \
./obj_client_tf_linux32/debug/c_tf_buff_banner.o \
./obj_client_tf_linux32/debug/c_tf_death_callingcard.o \
./obj_client_tf_linux32/debug/c_tf_freeaccount.o \
./obj_client_tf_linux32/debug/c_tf_fx.o \
./obj_client_tf_linux32/debug/c_tf_gamestats.o \
./obj_client_tf_linux32/debug/c_tf_glow.o \
./obj_client_tf_linux32/debug/c_tf_halloween.o \
./obj_client_tf_linux32/debug/c_tf_haptics.o \
./obj_client_tf_linux32/debug/c_tf_mvm_boss_progress_user.o \
./obj_client_tf_linux32/debug/c_tf_notification.o \
./obj_client_tf_linux32/debug/c_tf_objective_resource.o \
./obj_client_tf_linux32/debug/c_tf_passtime_ball.o \
./obj_client_tf_linux32/debug/c_tf_passtime_logic.o \
./obj_client_tf_linux32/debug/c_tf_player.o \
./obj_client_tf_linux32/debug/c_tf_playerresource.o \
./obj_client_tf_linux32/debug/c_tf_projectile_arrow.o \
./obj_client_tf_linux32/debug/c_tf_projectile_energy_ball.o \
./obj_client_tf_linux32/debug/c_tf_projectile_flare.o \
./obj_client_tf_linux32/debug/c_tf_projectile_rocket.o \
./obj_client_tf_linux32/debug/c_tf_stickybolt.o \
./obj_client_tf_linux32/debug/c_tf_taunt_prop.o \
./obj_client_tf_linux32/debug/c_tf_team.o \
./obj_client_tf_linux32/debug/c_tf_weapon_builder.o \
./obj_client_tf_linux32/debug/c_eyeball_boss.o \
./obj_client_tf_linux32/debug/c_headless_hatman.o \
./obj_client_tf_linux32/debug/c_merasmus.o \
./obj_client_tf_linux32/debug/c_merasmus_dancer.o \
./obj_client_tf_linux32/debug/c_zombie.o \
./obj_client_tf_linux32/debug/hud_basedeathnotice.o \
./obj_client_tf_linux32/debug/c_boss_alpha.o \
./obj_client_tf_linux32/debug/c_tf_base_boss.o \
./obj_client_tf_linux32/debug/c_tf_tank_boss.o \
./obj_client_tf_linux32/debug/c_tf_upgrades.o \
./obj_client_tf_linux32/debug/teammaterialproxy.o \
./obj_client_tf_linux32/debug/tf_abuse_report.o \
./obj_client_tf_linux32/debug/tf_autorp.o \
./obj_client_tf_linux32/debug/tf_coaching.o \
./obj_client_tf_linux32/debug/tf_consumables.o \
./obj_client_tf_linux32/debug/tf_demo_support.o \
./obj_client_tf_linux32/debug/tf_fx_blood.o \
./obj_client_tf_linux32/debug/tf_fx_christmaslights.o \
./obj_client_tf_linux32/debug/tf_fx_ejectbrass.o \
./obj_client_tf_linux32/debug/tf_fx_explosions.o \
./obj_client_tf_linux32/debug/tf_fx_impacts.o \
./obj_client_tf_linux32/debug/tf_fx_muzzleflash.o \
./obj_client_tf_linux32/debug/tf_fx_particleeffect.o \
./obj_client_tf_linux32/debug/tf_fx_taunteffects.o \
./obj_client_tf_linux32/debug/tf_fx_tracers.o \
./obj_client_tf_linux32/debug/tf_gameserver_management.o \
./obj_client_tf_linux32/debug/tf_hud_account.o \
./obj_client_tf_linux32/debug/tf_hud_achievement_tracker.o \
./obj_client_tf_linux32/debug/tf_hud_alert.o \
./obj_client_tf_linux32/debug/tf_hud_ammostatus.o \
./obj_client_tf_linux32/debug/tf_hud_annotationspanel.o \
./obj_client_tf_linux32/debug/tf_hud_arena_capturepoint.o \
./obj_client_tf_linux32/debug/tf_hud_arena_class_layout.o \
./obj_client_tf_linux32/debug/tf_hud_arena_notification.o \
./obj_client_tf_linux32/debug/tf_hud_arena_player_count.o \
./obj_client_tf_linux32/debug/tf_hud_arena_vs_panel.o \
./obj_client_tf_linux32/debug/tf_hud_arena_winpanel.o \
./obj_client_tf_linux32/debug/tf_hud_boss_health.o \
./obj_client_tf_linux32/debug/tf_hud_bowcharge.o \
./obj_client_tf_linux32/debug/tf_hud_building_status.o \
./obj_client_tf_linux32/debug/tf_hud_chat.o \
./obj_client_tf_linux32/debug/tf_hud_crosshair.o \
./obj_client_tf_linux32/debug/tf_hud_damageindicator.o \
./obj_client_tf_linux32/debug/tf_hud_deathnotice.o \
./obj_client_tf_linux32/debug/tf_hud_demomancharge.o \
./obj_client_tf_linux32/debug/tf_hud_demomanpipes.o \
./obj_client_tf_linux32/debug/tf_hud_disconnect_prompt.o \
./obj_client_tf_linux32/debug/tf_hud_disguise_status.o \
./obj_client_tf_linux32/debug/tf_hud_escort.o \
./obj_client_tf_linux32/debug/tf_hud_flagstatus.o \
./obj_client_tf_linux32/debug/tf_hud_freezepanel.o \
./obj_client_tf_linux32/debug/tf_hud_inspectpanel.o \
./obj_client_tf_linux32/debug/tf_hud_itemeffectmeter.o \
./obj_client_tf_linux32/debug/tf_hud_item_progress_tracker.o \
./obj_client_tf_linux32/debug/tf_hud_mainmenuoverride.o \
./obj_client_tf_linux32/debug/tf_hud_mann_vs_machine_loss.o \
./obj_client_tf_linux32/debug/tf_hud_mann_vs_machine_scoreboard.o \
./obj_client_tf_linux32/debug/tf_hud_mann_vs_machine_stats.o \
./obj_client_tf_linux32/debug/tf_hud_mann_vs_machine_status.o \
./obj_client_tf_linux32/debug/tf_hud_mann_vs_machine_victory.o \
./obj_client_tf_linux32/debug/tf_hud_match_status.o \
./obj_client_tf_linux32/debug/tf_hud_mediccallers.o \
./obj_client_tf_linux32/debug/tf_hud_mediccharge.o \
./obj_client_tf_linux32/debug/tf_hud_menu_engy_build.o \
./obj_client_tf_linux32/debug/tf_hud_menu_engy_destroy.o \
./obj_client_tf_linux32/debug/tf_hud_menu_eureka_teleport.o \
./obj_client_tf_linux32/debug/tf_hud_menu_spy_build.o \
./obj_client_tf_linux32/debug/tf_hud_menu_spy_disguise.o \
./obj_client_tf_linux32/debug/tf_hud_menu_taunt_selection.o \
./obj_client_tf_linux32/debug/tf_hud_minigame.o \
./obj_client_tf_linux32/debug/tf_hud_notification_panel.o \
./obj_client_tf_linux32/debug/tf_hud_objectivestatus.o \
./obj_client_tf_linux32/debug/tf_hud_passtime.o \
./obj_client_tf_linux32/debug/tf_hud_passtime_ball_offscreen_arrow.o \
./obj_client_tf_linux32/debug/tf_hud_passtime_reticle.o \
./obj_client_tf_linux32/debug/tf_hud_playerstatus.o \
./obj_client_tf_linux32/debug/tf_hud_pve_winpanel.o \
./obj_client_tf_linux32/debug/tf_hud_robot_destruction_status.o \
./obj_client_tf_linux32/debug/tf_hud_sapper_charge.o \
./obj_client_tf_linux32/debug/tf_hud_saxxycontest.o \
./obj_client_tf_linux32/debug/tf_hud_scope.o \
./obj_client_tf_linux32/debug/tf_hud_spectator_extras.o \
./obj_client_tf_linux32/debug/tf_hud_stalemate.o \
./obj_client_tf_linux32/debug/tf_hud_statpanel.o \
./obj_client_tf_linux32/debug/tf_hud_target_id.o \
./obj_client_tf_linux32/debug/tf_hud_teamgoal.o \
./obj_client_tf_linux32/debug/tf_hud_teamgoal_tournament.o \
./obj_client_tf_linux32/debug/tf_hud_teamswitch.o \
./obj_client_tf_linux32/debug/tf_hud_tournament.o \
./obj_client_tf_linux32/debug/tf_hud_training.o \
./obj_client_tf_linux32/debug/tf_hud_trainingmessage.o \
./obj_client_tf_linux32/debug/tf_hud_training_complete.o \
./obj_client_tf_linux32/debug/tf_hud_waitingforplayers_panel.o \
./obj_client_tf_linux32/debug/tf_hud_weaponselection.o \
./obj_client_tf_linux32/debug/tf_hud_winpanel.o \
./obj_client_tf_linux32/debug/tf_input_main.o \
./obj_client_tf_linux32/debug/tf_prediction.o \
./obj_client_tf_linux32/debug/tf_presence.o \
./obj_client_tf_linux32/debug/tf_proxyentity.o \
./obj_client_tf_linux32/debug/tf_proxyplayer.o \
./obj_client_tf_linux32/debug/tf_rendertargets.o \
./obj_client_tf_linux32/debug/tf_replay.o \
./obj_client_tf_linux32/debug/tf_shared_content_manager.o \
./obj_client_tf_linux32/debug/tf_steamstats.o \
./obj_client_tf_linux32/debug/tf_streams.o \
./obj_client_tf_linux32/debug/tf_teamstatus.o \
./obj_client_tf_linux32/debug/tf_time_panel.o \
./obj_client_tf_linux32/debug/tf_tips.o \
./obj_client_tf_linux32/debug/tf_viewrender.o \
./obj_client_tf_linux32/debug/backgroundpanel.o \
./obj_client_tf_linux32/debug/blueprint_panel.o \
./obj_client_tf_linux32/debug/character_info_panel.o \
./obj_client_tf_linux32/debug/charinfo_armory_subpanel.o \
./obj_client_tf_linux32/debug/charinfo_loadout_subpanel.o \
./obj_client_tf_linux32/debug/class_loadout_panel.o \
./obj_client_tf_linux32/debug/collection_crafting_panel.o \
./obj_client_tf_linux32/debug/crafting_panel.o \
./obj_client_tf_linux32/debug/crate_detail_panels.o \
./obj_client_tf_linux32/debug/drawing_panel.o \
./obj_client_tf_linux32/debug/dynamic_recipe_subpanel.o \
./obj_client_tf_linux32/debug/halloween_offering_panel.o \
./obj_client_tf_linux32/debug/item_ad_panel.o \
./obj_client_tf_linux32/debug/item_quickswitch.o \
./obj_client_tf_linux32/debug/item_slot_panel.o \
./obj_client_tf_linux32/debug/loadout_preset_panel.o \
./obj_client_tf_linux32/debug/modelimagepanel.o \
./obj_client_tf_linux32/debug/ObjectControlPanel.o \
./obj_client_tf_linux32/debug/quest_item_panel.o \
./obj_client_tf_linux32/debug/quest_log_panel.o \
./obj_client_tf_linux32/debug/quest_notification_panel.o \
./obj_client_tf_linux32/debug/report_player_dialog.o \
./obj_client_tf_linux32/debug/sc_hinticon.o \
./obj_client_tf_linux32/debug/select_player_dialog.o \
./obj_client_tf_linux32/debug/softline.o \
./obj_client_tf_linux32/debug/tf_store.o \
./obj_client_tf_linux32/debug/tf_store_page_base.o \
./obj_client_tf_linux32/debug/tf_store_panel_base.o \
./obj_client_tf_linux32/debug/tf_store_preview_item_base.o \
./obj_client_tf_linux32/debug/tf_store_page.o \
./obj_client_tf_linux32/debug/tf_store_page_maps.o \
./obj_client_tf_linux32/debug/tf_store_panel.o \
./obj_client_tf_linux32/debug/tf_store_preview_item.o \
./obj_client_tf_linux32/debug/tf_store_mapstamps_info_dialog.o \
./obj_client_tf_linux32/debug/tf_store_page2.o \
./obj_client_tf_linux32/debug/tf_store_page_maps2.o \
./obj_client_tf_linux32/debug/tf_store_panel2.o \
./obj_client_tf_linux32/debug/tf_store_preview_item2.o \
./obj_client_tf_linux32/debug/strange_count_transfer_panel.o \
./obj_client_tf_linux32/debug/testitem_dialog.o \
./obj_client_tf_linux32/debug/testitem_root.o \
./obj_client_tf_linux32/debug/tf_arenateammenu.o \
./obj_client_tf_linux32/debug/tf_asyncpanel.o \
./obj_client_tf_linux32/debug/tf_badge_panel.o \
./obj_client_tf_linux32/debug/tf_classmenu.o \
./obj_client_tf_linux32/debug/tf_clientscoreboard.o \
./obj_client_tf_linux32/debug/tf_controls.o \
./obj_client_tf_linux32/debug/tf_giveawayitempanel.o \
./obj_client_tf_linux32/debug/tf_imagepanel.o \
./obj_client_tf_linux32/debug/tf_intromenu.o \
./obj_client_tf_linux32/debug/tf_item_card_panel.o \
./obj_client_tf_linux32/debug/tf_item_inspection_panel.o \
./obj_client_tf_linux32/debug/tf_item_pickup_panel.o \
./obj_client_tf_linux32/debug/tf_layeredmappanel.o \
./obj_client_tf_linux32/debug/tf_leaderboardpanel.o \
./obj_client_tf_linux32/debug/tf_lobbypanel.o \
./obj_client_tf_linux32/debug/tf_lobbypanel_casual.o \
./obj_client_tf_linux32/debug/tf_lobbypanel_comp.o \
./obj_client_tf_linux32/debug/tf_lobbypanel_mvm.o \
./obj_client_tf_linux32/debug/tf_lobby_container_frame.o \
./obj_client_tf_linux32/debug/tf_lobby_container_frame_casual.o \
./obj_client_tf_linux32/debug/tf_lobby_container_frame_comp.o \
./obj_client_tf_linux32/debug/tf_lobby_container_frame_mvm.o \
./obj_client_tf_linux32/debug/tf_mapinfomenu.o \
./obj_client_tf_linux32/debug/tf_matchmaking_dashboard.o \
./obj_client_tf_linux32/debug/tf_matchmaking_dashboard_new_match_found.o \
./obj_client_tf_linux32/debug/tf_matchmaking_dashboard_next_map_voting.o \
./obj_client_tf_linux32/debug/tf_matchmaking_dashboard_next_map_winner.o \
./obj_client_tf_linux32/debug/tf_match_join_handlers.o \
./obj_client_tf_linux32/debug/tf_match_summary.o \
./obj_client_tf_linux32/debug/tf_mouseforwardingpanel.o \
./obj_client_tf_linux32/debug/tf_particlepanel.o \
./obj_client_tf_linux32/debug/tf_ping_panel.o \
./obj_client_tf_linux32/debug/tf_playermodelpanel.o \
./obj_client_tf_linux32/debug/tf_playerpanel.o \
./obj_client_tf_linux32/debug/tf_pvp_rank_panel.o \
./obj_client_tf_linux32/debug/tf_roundinfo.o \
./obj_client_tf_linux32/debug/tf_spectatorgui.o \
./obj_client_tf_linux32/debug/tf_statsummary.o \
./obj_client_tf_linux32/debug/tf_teammenu.o \
./obj_client_tf_linux32/debug/tf_textwindow.o \
./obj_client_tf_linux32/debug/tf_training_ui.o \
./obj_client_tf_linux32/debug/tf_vgui_video.o \
./obj_client_tf_linux32/debug/tf_viewport.o \
./obj_client_tf_linux32/debug/tf_warinfopanel.o \
./obj_client_tf_linux32/debug/vgui_critpanel.o \
./obj_client_tf_linux32/debug/vgui_pda_panel.o \
./obj_client_tf_linux32/debug/vgui_rootpanel_tf.o \
./obj_client_tf_linux32/debug/vgui_rotation_slider.o \
./obj_client_tf_linux32/debug/timematerialproxy.o \
./obj_client_tf_linux32/debug/toggletextureproxy.o \
./obj_client_tf_linux32/debug/toolframework_client.o \
./obj_client_tf_linux32/debug/train.o \
./obj_client_tf_linux32/debug/vgui_avatarimage.o \
./obj_client_tf_linux32/debug/vgui_basepanel.o \
./obj_client_tf_linux32/debug/vgui_bitmapbutton.o \
./obj_client_tf_linux32/debug/vgui_bitmapimage.o \
./obj_client_tf_linux32/debug/vgui_bitmappanel.o \
./obj_client_tf_linux32/debug/vgui_centerstringpanel.o \
./obj_client_tf_linux32/debug/vgui_consolepanel.o \
./obj_client_tf_linux32/debug/vgui_debugoverlaypanel.o \
./obj_client_tf_linux32/debug/vgui_fpspanel.o \
./obj_client_tf_linux32/debug/vgui_game_viewport.o \
./obj_client_tf_linux32/debug/vgui_grid.o \
./obj_client_tf_linux32/debug/vgui_int.o \
./obj_client_tf_linux32/debug/vgui_loadingdiscpanel.o \
./obj_client_tf_linux32/debug/vgui_messagechars.o \
./obj_client_tf_linux32/debug/vgui_netgraphpanel.o \
./obj_client_tf_linux32/debug/vgui_schemevisualizer.o \
./obj_client_tf_linux32/debug/vgui_slideshow_display_screen.o \
./obj_client_tf_linux32/debug/vgui_video.o \
./obj_client_tf_linux32/debug/vgui_video_player.o \
./obj_client_tf_linux32/debug/view.o \
./obj_client_tf_linux32/debug/viewangleanim.o \
./obj_client_tf_linux32/debug/ViewConeImage.o \
./obj_client_tf_linux32/debug/viewdebug.o \
./obj_client_tf_linux32/debug/viewpostprocess.o \
./obj_client_tf_linux32/debug/viewrender.o \
./obj_client_tf_linux32/debug/view_beams.o \
./obj_client_tf_linux32/debug/view_effects.o \
./obj_client_tf_linux32/debug/view_scene.o \
./obj_client_tf_linux32/debug/voice_menu.o \
./obj_client_tf_linux32/debug/warp_overlay.o \
./obj_client_tf_linux32/debug/WaterLODMaterialProxy.o \
./obj_client_tf_linux32/debug/weapons_resource.o \
./obj_client_tf_linux32/debug/weapon_selection.o \
./obj_client_tf_linux32/debug/WorldDimsProxy.o \
\
/usr/local/lib/libprotobuf.a \
\
../../lib/public/linux32/tier1.a \
../../lib/common/linux32/replay_common.a \
../../lib/public/linux32/bitmap.a \
../../lib/public/linux32/choreoobjects.a \
../../lib/public/linux32/dmxloader.a \
../../lib/public/linux32/mathlib.a \
../../lib/public/linux32/matsys_controls.a \
../../lib/public/linux32/particles.a \
../../lib/public/linux32/tier1.a \
../../lib/public/linux32/tier2.a \
../../lib/public/linux32/tier3.a \
../../lib/public/linux32/vgui_controls.a \
../../lib/public/linux32/vtf.a \
../../lib/common/linux32/libcrypto.a \
../../lib/public/linux32/libz.a \
../../lib/public/linux32/gcsdk.a \
../../lib/public/linux32/vpklib.a \
../../lib/common/linux32/libcrypto.a \
../../lib/common/linux32/libcryptopp.a \
../../lib/common/linux32/libjpeg.a \
../../lib/public/linux32/libpng.a \
../../lib/public/linux32/libz.a \
\
-L../../lib/public/linux32 -ltier0 \
-L../../lib/public/linux32 -lvstdlib \
-L../../lib/public/linux32 -lsteam_api \
-L../../lib/public/linux32 -lsteamnetworkingsockets  -lrt  -Wl,--end-group -lm -ldl /usr/lib/gcc/x86_64-pc-linux-gnu/$(gcc --version | head -n 1 | awk '{print $3}')/../../../../lib32/libstdc++.so \
-lpthread -l:ld-linux.so.2 -Wl,--version-script=../../devtools/version_script.linux.txt \
\
>> ../../../link.log 2>&1
echo -e "\n--------------------- gcc linker PASSED for: \t\t client.so (debug)" >> ../../../link.log
